const HEADLINES = [
  'Gatsby Silly Site Challenge Announced!',
  'Headlines brought to you by SimCity and MSNBSea.',
  'Lab Rat Union Files Class Action Against Scientists',
  'Doughnuts: Is There Anything They Can\'t Do?',
  'New Yorker Goes to Italy, Complains About Pizza',
  'Daily Special At Restaurant Found To Be Big Fat Lie',
  'Eyes Move While Reading Tickers, Scientists Speculate',
  'Pooper Scoopers Urged When Walking Dogs',
  'Studies Show Most Mispronounce \'Zsdersw\'',
  'Experts Say Gravy Tastes Better When Loudly Slurped',
  'Bring Back Marquee Tag, Disgruntled Nerds Demand', 
  'Traveling Technician Talks Transmissions Tuesday',
  'A Rising Sea Lifts All Boats\', Claims Oil Lobbyist',
  'Heard on the Street: Kitty Kibble Shortage Imminent',
  'Kitty Kibble Futures Spike; Consumers Stockpile',
  'Local Merchants Puzzled By Rumors: \'We Have Plenty\'',
  'Kitties Concerned By Shortage; Owners In Panic',
  'Kitty Kibble Association Denies Kitty Kibble Rumors',
  'Is Kitty Kibble Shortage Real? Authorities Say No',
  'Rumors Persist In Kitty Kibble Shortage',
  'Kitty Kibble Factory Fuels Shortage Rumors',
  'Enough Kitty Kibble For 20 Years, Experts Agree',
  'Kitties Want Answers On Kitty Kibble Shortage',
  'No Kitty Kibble Shortage, Officials Insist',
  'Kitties Skeptical',
  'All Raccoons Cheat At Poker, Animal Researchers Say',
  'Ancient Meteorite Revealed To Be Burnt Burger',
  'Lying Found To Be Effective Calorie Reducer',
  'Man Bites Dog, Dog Sues Man',
  'Man Discovers Wife Actually Rare Yucca Plant',
  'I Was Framed, Jokes Local Artist',
  'Monkey Sees, Monkey Does',
  'Lobster Mobster Caught Red-Handed',
  'Pigeon Alert! Extreme Pigeon Danger!',
  'Spotted Owl Spotted',
  'Pistol Packing Punks Pilfer Precious Petunias',
  'This Space For Rent',
  'Weather Likely To Become Different Before Changing',
];

export const TYPED_OPTIONS = {
  strings: HEADLINES,
  backDelay: 4000,
  showCursor: false,
  loop: true,
};