const GIF_CONFIG = [
  {
    src: require('./assets/40oz.gif'), 
    alt: '40oz.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/aim-rain.gif'), 
    alt: 'aim-rain.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/blinds.gif'), 
    alt: 'blinds.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/boxes.gif'), 
    alt: 'boxes.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/boxes-color.gif'), 
    alt: 'boxes-color.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/bunnies.gif'), 
    alt: 'bunnies.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/burger.gif'), 
    alt: 'burger.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/cd.gif'), 
    alt: 'cd.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/chip.gif'), 
    alt: 'chip.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/croak.gif'), 
    alt: 'croak.gif',
    canBeForeground: true, 
    canBeBackground: false, 
  },
  {
    src: require('./assets/cubes-gif.gif'), 
    alt: 'cubes-gif.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/cubes.gif'), 
    alt: 'cubes.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/cyberpunk.gif'), 
    alt: 'cyberpunk.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/dancing.gif'), 
    alt: 'dancing.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/ditto.gif'), 
    alt: 'ditto.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/doge.gif'), 
    alt: 'doge.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/donut.gif'), 
    alt: 'donut.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/dorito.gif'), 
    alt: 'dorito.gif',
    canBeForeground: true, 
    canBeBackground: false, 
  },
  {
    src: require('./assets/email.gif'), 
    alt: 'email.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/finish.gif'), 
    alt: 'finish.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/flash-drive.gif'), 
    alt: 'flash-drive.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/flip-phone.gif'), 
    alt: 'flip-phone.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/floating-cd.gif'), 
    alt: 'floating-cd.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/floppy-disk.gif'), 
    alt: 'floppy-disk.gif',
    canBeForeground: true, 
    canBeBackground: false, 
  },
  {
    src: require('./assets/flying-money.gif'), 
    alt: 'flying-money.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/geo.gif'), 
    alt: 'geo.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/ipod-classic.gif'), 
    alt: 'ipod-classic.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/jog.gif'), 
    alt: 'jog.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/key.gif'), 
    alt: 'key.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/lacroix.gif'), 
    alt: 'lacroix.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/laptops.gif'), 
    alt: 'laptops.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/limewire.gif'), 
    alt: 'limewire.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/links.gif'), 
    alt: 'links.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/mario-cloud.gif'), 
    alt: 'mario-cloud.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/more-cubes.gif'), 
    alt: 'more-cubes.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/ms-dos.gif'), 
    alt: 'ms-dos.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/n64.gif'), 
    alt: 'n64.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/nyan-cat.gif'), 
    alt: 'nyan-cat.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/pawns.gif'), 
    alt: 'pawns.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/netscape.gif'), 
    alt: 'netscape.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/pc.gif'), 
    alt: 'pc.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/pepsi.gif'), 
    alt: 'pepsi.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/pills.gif'), 
    alt: 'pills.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/points.gif'), 
    alt: 'points.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/pop.gif'), 
    alt: 'pop.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/rose.gif'), 
    alt: 'rose.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/running-cat.gif'), 
    alt: 'running-cat.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/running-wolf.gif'), 
    alt: 'running-wolf.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/shark.gif'), 
    alt: 'shark.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/shiba.gif'), 
    alt: 'shiba.gif',
    canBeForeground: true, 
    canBeBackground: false, 
  },
  {
    src: require('./assets/sink.gif'), 
    alt: 'sink.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/stab.gif'), 
    alt: 'stab.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/twist.gif'), 
    alt: 'twist.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/unicorn.gif'), 
    alt: 'unicorn.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/vhs.gif'), 
    alt: 'vhs.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/walking-wolf.gif'), 
    alt: 'walking-wolf.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/wave.gif'), 
    alt: 'wave.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/wavy-cup.gif'), 
    alt: 'wavy-cup.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/what.gif'), 
    alt: 'what.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/wifi.gif'), 
    alt: 'wifi.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/windows-flag.gif'), 
    alt: 'windows-flag.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/windows-paint.gif'), 
    alt: 'windows-paint.gif',
    canBeForeground: true, 
    canBeBackground: true, 
  },
  {
    src: require('./assets/windows-xp.gif'), 
    alt: 'windows-xp.gif',
    canBeForeground: false, 
    canBeBackground: true, 
  },
];

export const FOREGROUND_GIFS = GIF_CONFIG.filter(gif => gif.canBeForeground);
export const BACKGROUND_GIFS = GIF_CONFIG.filter(gif => gif.canBeBackground);